### PR TITLE
Circleci

### PR DESCRIPTION
**Pull request by ebabel**

### CODE REVIEW

**Comment by ebabel** [comment]
@ivnvrmn Wups this has "ebabel" in it. sorry
and you might have to allow circle.ci to have access, super easy/quick

**Comment by ivnvrmn** [comment]
@ebabel how can I allow access?

**Comment by ebabel** [comment]
Go here, hopefully it just walks you through after signing and connecting your github
https://circleci.com/gh/ivnvrmn/CryptoMoon

**Comment by ivnvrmn** [comment]
@ebabel connected

**Comment by ivnvrmn** [comment]
@ebabel what version of Android Studio you have?

**Comment by ebabel** [comment]
3.0, why did I do something that is incompatible with yours?

**Comment by ivnvrmn** [comment]
@ebabel when I updated to 3.0, project is not built. With some error with kapt.
What updates have you made in gradle project and app? Can you show me that changes?

**Comment by ivnvrmn** [comment]
@ebabel or you just didn't update gradle file? It doesn't compile when I try to update gradle to 3.0.0 and set buildToolsVersion to 26.0.2

**Comment by ebabel** [comment]
@ivnvrmn This talks about apt needing to be changed: https://stackoverflow.com/a/42574851/247325 
I'm trying to see if I get get it going

**Comment by ebabel** [comment]
man, what a dumpster fire this kapt thing is. I can't figure it out.

**Comment by ivnvrmn** [comment]
@ebabel I'm too, so just don't update gradle. But it's not good, had to solve this

**Comment by ivnvrmn** [comment]
@ebabel fixed with help @danmazzella thank you!

**Comment by ebabel** [comment]
@ivnvrmn thats fantastic! I think I was close but that room update was tough

**Comment by danmazzella** [comment]
Awesome, I'm glad I was able to help!

**Pull request merged**
